theme: jekyll-theme-architect 
title: HDSD Chatbot ViAIBOT
description: Trang web hướng dẫn sử dụng Trợ lý ảo AI-ViAIBOT.
show_downloads: false 
plugins:
  - jekyll-seo-tag
author:
  name: Phan Thanh Giảng
  email: giangphan028@gmail.com
social:
  github: giangcse
  twitter: giangpt2808
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty