theme: jekyll-theme-cayman 
title: HDSD Chatbot VIAIBOT
description: Trang web hướng dẫn sử dụng Trợ lý ảo AI-VIAIBOT.
show_downloads: false 
plugins:
  - jekyll-seo-tag
author:
  name: Phan Thanh Giảng
  email: giang@giangpt.dev
  url: https://giangpt.dev/
  department: Phòng Giải pháp - TT Kinh doanh Giải pháp - VNPT Vĩnh Long
social:
  github: giangcse
  twitter: giangpt2808
  telegram: giang_cse
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  toc_levels: 1..6
  auto_ids: true 
permalink: pretty
encoding: UTF-8